dist: trusty
sudo: require
language: cpp

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - sourceline: "ppa:ubuntu-toolchain-r/test"
          packages:
            - g++-6
            - cmake
      env: COMPILER=g++-6

before_script:
  - wget https://github.com/g-truc/glm/releases/download/0.9.9.0/glm-0.9.9.0.zip -O /tmp/glm.zip
  - unzip /tmp/glm.zip -d /tmp

script: 
  - mkdir build
  - cd build
  - cmake -DCMAKE_CXX_COMPILER=$COMPILER -DTINYNURBS_USE_OWN_GLM=OFF -DGLM_ROOT_DIR=/tmp/glm ..
  - make
  - make test
